name: Tools
on:
  pull_request:
    paths:
      - 'tools/**'
  push:
    paths:
      - 'tools/**'
    branches: [develop]
jobs:
  build:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_8-core
    steps:
      - uses: actions/checkout@v4
      - run: make tools
